# Set aliases
alias ls="ls -G"
alias ll="ls -lah"
alias grep="grep --color=auto"
alias v="$EDITOR"
alias g="git"
alias f="vifm"
alias dotf="cd $HOME/dotfiles/"
alias wfm="cd $HOME/Documents/projects/wfm/"
alias aat="cd $HOME/Documents/projects/wfm/aat-processor/"
alias rts="cd $HOME/Documents/projects/wfm/rts/"
alias wss="cd $HOME/Documents/projects/wfm/websocket-service/"
alias wss="cd $HOME/Documents/projects/wfm/websocket-service/"
alias adh="cd $HOME/Documents/projects/wfm/adherence/"
alias ssp="cd $HOME/Documents/projects/wfm/snappy-stream-processor/"
alias twf="cd $HOME/Documents/projects/wfm/temporal-workflows/"
alias uas="cd $HOME/Documents/projects/wfm/uas/"
alias sapi="cd $HOME/Documents/projects/wfm/storage-api/"
alias v2="cd $HOME/Documents/projects/wfm/tymeshift-laravel-app/"
