#!/bin/sh

case $BLOCK_BUTTON in
    1) $TERMINAL -e nmtui ;;
esac

if [[ "$(cat /sys/class/net/w*/operstate)" == "up" ]]; then
    wifi=$(grep '^w' /proc/net/wireless | awk '{ print "" " " int($3 * 100 / 70) "%" }')
fi

eth=$(cat /sys/class/net/e*/operstate | sed "s/down//;s/up//")

echo "$eth $wifi"

