#!/bin/sh

for x in "$(xrdb -query | sed "s/.*\./export /g;s/:\s*/=\"/g;s/$/\"/g")"; do eval "$x"; done

dmenu_run -i -l 10 -nb "$background" -nf "$color7" \
	-sb "$background" -sf "$colorBD" \
	-fn "$font" 
# echo "$background" "$foreground" "$font"
